hhru/AdaptationProject

backend/pom.xml, backend/src/etc/adaptation/service.properties, backend/src/main/java/ru/hh/school/adaptation/AdaptationCommonConfig.java, backend/src/main/java/ru/hh/school/adaptation/AdaptationMain.java, backend/src/main/java/ru/hh/school/adaptation/AdaptationServletConfig.java, backend/src/main/java/ru/hh/school/adaptation/ProdConfig.java, backend/src/main/java/ru/hh/school/adaptation/dao/UserDao.java, backend/src/main/java/ru/hh/school/adaptation/dto/HhUserInfoDto.java, backend/src/main/java/ru/hh/school/adaptation/dto/UserDto.java, backend/src/main/java/ru/hh/school/adaptation/entities/User.java, backend/src/main/java/ru/hh/school/adaptation/filters/AuthFilter.java, backend/src/main/java/ru/hh/school/adaptation/misc/UserSession.java, backend/src/main/java/ru/hh/school/adaptation/resources/AuthResource.java, backend/src/main/java/ru/hh/school/adaptation/resources/MainResource.java, backend/src/main/java/ru/hh/school/adaptation/services/UserService.java, backend/src/main/java/ru/hh/school/adaptation/services/auth/AuthService.java, backend/src/main/java/ru/hh/school/adaptation/services/auth/HhApiService.java, backend/src/main/resources/db/migration/V3__Create_employee_hr_tables.sql, backend/src/test/java/ru/hh/school/adaptation/TestConfig.java
Сервис авторизации.
1. Переход на NaB 3.5.0
2. Добавлены properties для oauth
3. `AuthService` — сервис авторизации
4. `UserService` — минимальный набор сервиса пользователя для авторизации
5. `HhApiService` — сервис для общения с API HH
6. `UserSession` — сессия пользователя
7. `UserDto` — дтошка пользователя
8. `UserDao` — добавил электропочту
9. `HhUserInfoDto` — дтошка для API HH
10. `AuthResource` — ресурсы авторизации
=> TASK-5: authorization

backend/src/main/java/ru/hh/school/adaptation/AdaptationCommonConfig.java, backend/src/main/java/ru/hh/school/adaptation/dao/TaskDao.java, backend/src/main/java/ru/hh/school/adaptation/dao/TaskFormDao.java, backend/src/main/java/ru/hh/school/adaptation/dto/TaskDto.java, backend/src/main/java/ru/hh/school/adaptation/dto/TaskFormDto.java, backend/src/main/java/ru/hh/school/adaptation/entities/Employee.java, backend/src/main/java/ru/hh/school/adaptation/entities/Task.java, backend/src/main/java/ru/hh/school/adaptation/entities/TaskForm.java, backend/src/main/java/ru/hh/school/adaptation/resources/TaskResource.java, backend/src/main/java/ru/hh/school/adaptation/services/TaskService.java, backend/src/main/resources/db/migration/V5__Create_tasks_tables.sql, frontend/src/components/AddTask.js, frontend/src/components/App.js
Бэкэнд и фронтэнд для формы заполнения задач по уникальному адресу.
=> Task 22: Форма задач с уникальным URI

frontend/src/components/App.js, frontend/src/components/EmployeePage.js, frontend/src/components/HomePage.js, frontend/src/components/tasks/AddTask.js, frontend/src/components/tasks/EmployeeTasksModal.js, frontend/src/components/tasks/FunctionalTasks.js
Добавлена модалка с задачами на карточку сотрудника
Для корпоративных задач сделаны нередактируемые "заглушки" на странице редактирования задач и на модалке просмотра.
Добавлена кнопка для скачивания docx-файла.
=> TASK-26 Задачи на карточке сотрудника

backend/src/main/java/ru/hh/school/adaptation/dto/UserInfoDto.java, backend/src/main/java/ru/hh/school/adaptation/exceptions/AccessDeniedException.java, backend/src/main/java/ru/hh/school/adaptation/resources/AuthResource.java, backend/src/main/java/ru/hh/school/adaptation/services/auth/AuthService.java
1. Add /user resource.
2. Update BACK_URL.
3. Add UserInfo DTO
=> Authorization improvement

backend/src/main/java/ru/hh/school/adaptation/resources/EmployeeResource.java, backend/src/main/java/ru/hh/school/adaptation/services/CommentService.java, backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, backend/src/main/java/ru/hh/school/adaptation/services/documents/TaskDocumentGenerator.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/QuestionnaireStep.java
https://jira.hh.ru/browse/ADAPT-11
=> AD-11 fix 500 for probation result

backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, backend/src/main/java/ru/hh/school/adaptation/services/QuestionnaireService.java, backend/src/main/java/ru/hh/school/adaptation/services/TaskService.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/AddStep.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/QuestionnaireStep.java
https://jira.hh.ru/browse/ADAPT-9
=> AD-9 parametrize host name

backend/src/main/java/ru/hh/school/adaptation/dto/PersonalDto.java, backend/src/main/java/ru/hh/school/adaptation/dto/UserDto.java, backend/src/main/java/ru/hh/school/adaptation/dto/UserInfoDto.java, backend/src/main/java/ru/hh/school/adaptation/entities/PersonalInfo.java, backend/src/main/java/ru/hh/school/adaptation/services/PersonalInfoService.java, backend/src/main/resources/db/migration/V2__Create_employee_hr_tables.sql, frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js, frontend/src/components/EmployeePage.js, frontend/src/toolkit/Employee.js, frontend/src/toolkit/PersonCreator.js, frontend/src/toolkit/PersonEdit.js
https://jira.hh.ru/browse/ADAPT-15
=> AD-15 add subdivision field

frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js, frontend/src/components/EmployeePage.js, frontend/src/components/ListEmployees.js
https://jira.hh.ru/browse/ADAPT-14
=> ADAPT-14 rename chief and dismiss messages

backend/src/main/java/ru/hh/school/adaptation/misc/CommonUtils.java
https://jira.hh.ru/browse/ADAPT-13
=> ADAPT-13 fix (null) in makeFioFromPersonalInfo's return value

backend/src/main/java/ru/hh/school/adaptation/misc/CommonUtils.java
https://jira.hh.ru/browse/ADAPT-20
=> AD-20 fix unused import

backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js, frontend/src/components/EmployeePage.js
https://jira.hh.ru/browse/ADAPT-25
=> AD-25 rename mentor messages

frontend/src/toolkit/LabeledInput.js
https://jira.hh.ru/browse/ADAPT-23
Изменил layout формы редактирования c `|--|----------|` на `|----|--------|`
=> AD-23 fix PersonEdit layout

frontend/src/components/AddEmployee.js, frontend/src/toolkit/GenderEdit.js, frontend/src/toolkit/LabeledInputWithHelp.js, frontend/src/toolkit/Person.js, frontend/src/toolkit/PersonEdit.js, frontend/src/toolkit/User.js
https://jira.hh.ru/browse/ADAPT-29
=> AD-29 add LabeledInputWithHelp + layout fix

backend/src/main/java/ru/hh/school/adaptation/resources/PersonalInfoResource.java, backend/src/main/java/ru/hh/school/adaptation/services/PersonalInfoService.java, frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js
https://jira.hh.ru/browse/ADAPT-24
=> AD-24 add personInfo validation

frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js
https://jira.hh.ru/browse/ADAPT-22
=> AD-22 remove data object from console.log

frontend/src/components/EditEmployee.js, frontend/src/components/EmployeePage.js, frontend/src/components/ListEmployees.js, frontend/src/components/app.css
https://jira.hh.ru/browse/ADAPT-32
=> AD-32 remove number column

frontend/package.json, frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js, frontend/src/toolkit/Employee.js, frontend/src/toolkit/Person.js, frontend/src/toolkit/PersonCreator.js, frontend/src/toolkit/PersonEdit.js, frontend/src/toolkit/User.js, frontend/yarn.lock
https://jira.hh.ru/browse/ADAPT-31
=> AD-31 add validation to frontend

frontend/src/components/App.js, frontend/src/components/Restrictor.js
Дичайше поправлена логика доступа к страницам сайта. Логика проверки авторизации вынесена в отдельный класс. Страницы для каждого типа авторизации могут быть свёрстаны по-своему.
=> AD-12 fix app access logic

backend/src/main/java/ru/hh/school/adaptation/resources/EmployeeResource.java, backend/src/main/java/ru/hh/school/adaptation/services/documents/DocumentGenerator.java, backend/src/main/java/ru/hh/school/adaptation/services/documents/TaskDocumentGenerator.java
https://jira.hh.ru/browse/ADAPT-40
=> AD-40 hotfix 500 for get tasks

backend/src/main/java/ru/hh/school/adaptation/AdaptationCommonConfig.java, backend/src/main/java/ru/hh/school/adaptation/AdaptationMain.java, backend/src/main/java/ru/hh/school/adaptation/dao/ScheduledMailDao.java, backend/src/main/java/ru/hh/school/adaptation/entities/ScheduledMail.java, backend/src/main/java/ru/hh/school/adaptation/services/ScheduledMailService.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/AddStep.java, backend/src/main/resources/db/migration/V6__Create_questionnaire_table.sql
https://jira.hh.ru/browse/ADAPT-36
=> AD-36 add scheduler for mail

backend/pom.xml, backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, backend/src/main/java/ru/hh/school/adaptation/services/MailService.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/AddStep.java
https://jira.hh.ru/browse/ADAPT-38
=> AD-38 migrate to icalendar library

backend/src/main/java/ru/hh/school/adaptation/dao/EmployeeDao.java, backend/src/main/java/ru/hh/school/adaptation/resources/EmployeeResource.java, backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/AddStep.java, frontend/src/components/EmployeePage.js
https://jira.hh.ru/browse/ADAPT-41
=> AD-41 add resend chief task button

backend/src/main/java/ru/hh/school/adaptation/dto/EmployeeBriefDto.java, backend/src/main/java/ru/hh/school/adaptation/dto/EmployeeCreateDto.java, backend/src/main/java/ru/hh/school/adaptation/dto/EmployeeDto.java, backend/src/main/java/ru/hh/school/adaptation/dto/EmployeeUpdateDto.java, backend/src/main/java/ru/hh/school/adaptation/entities/Employee.java, backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, backend/src/main/java/ru/hh/school/adaptation/services/TransitionService.java, backend/src/main/java/ru/hh/school/adaptation/services/documents/TaskDocumentGenerator.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/AddStep.java, backend/src/main/resources/db/migration/V1_7__AD-61.sql, frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js, frontend/src/toolkit/Employee.js
https://jira.hh.ru/browse/ADAPT-61
=> AD-61 add new interim_date and final_date

frontend/src/components/AdminPage.js
Добавлена кнопка для перехода на тестовый стенд и обратно
=> ADAPT-62 add environment toggle button

frontend/package.json, frontend/yarn.lock
=> up bootstrap version

backend/pom.xml, backend/run.sh, backend/src/main/java/ru/hh/school/adaptation/AdaptationCommonConfig.java, backend/src/main/java/ru/hh/school/adaptation/AdaptationServletConfig.java, backend/src/main/java/ru/hh/school/adaptation/resources/FileUploadResource.java, backend/src/main/java/ru/hh/school/adaptation/services/FileUploadService.java, docker-compose.yml, frontend/src/components/EmployeeAttachModal.js, frontend/src/components/EmployeePage.js, frontend/src/components/app.css
https://jira.hh.ru/browse/ADAPT-57
=> ADAPT-57 attach files

frontend/src/components/AddEmployee.js, frontend/src/components/EditEmployee.js, frontend/src/components/app.css, frontend/src/toolkit/Person.js
https://jira.hh.ru/browse/ADAPT-46
=> ADAPT-46 remove default chief

backend/src/main/java/ru/hh/school/adaptation/misc/CommonUtils.java, backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, backend/src/main/java/ru/hh/school/adaptation/services/MailService.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/AddStep.java
https://jira.hh.ru/browse/ADAPT-72
=> ADAPT-72 improve ical: hr as organizer, informative subject and summary

frontend/src/components/Header.js, frontend/src/components/HomePage.js, frontend/src/components/app.css
https://jira.hh.ru/browse/ADAPT-21
/ (╯°□°）╯︵ ┻━┻
=> ADAPT-21 collapsing header

frontend/src/components/ListEmployees.js
https://jira.hh.ru/browse/ADAPT-75
Сохраняем количество отображаемых строк в таблице со списком сотрудников
=> ADAPT-75 save some employee table params to local storage

frontend/src/components/Header.js, frontend/src/components/ListEmployees.js
https://jira.hh.ru/browse/ADAPT-84
=> ADAPT-84 fix header links

backend/Dockerfile, backend/pom.xml, backend/src/main/java/ru/hh/school/adaptation/services/documents/DocumentGenerator.java
https://jira.hh.ru/browse/ADAPT-79
=> ADAPT-79 run adaptation with java 10

backend/src/main/java/ru/hh/school/adaptation/services/documents/TaskDocumentGenerator.java
https://jira.hh.ru/browse/ADAPT-19
=> ADAPT-19 date format for docs

frontend/src/components/EmployeePage.js
https://jira.hh.ru/browse/ADAPT-86
=> ADAPT-86 fix hard bag

.gitignore, backend/src/main/java/ru/hh/school/adaptation/dao/ScheduledMailDao.java, backend/src/main/java/ru/hh/school/adaptation/entities/ScheduledMail.java, backend/src/main/java/ru/hh/school/adaptation/entities/ScheduledMailType.java, backend/src/main/java/ru/hh/school/adaptation/services/EmployeeService.java, backend/src/main/java/ru/hh/school/adaptation/services/MailService.java, backend/src/main/java/ru/hh/school/adaptation/services/ScheduledMailService.java, backend/src/main/java/ru/hh/school/adaptation/services/workflow/AddStep.java, backend/src/main/resources/db/migration/V1_9__AD-90.sql
https://jira.hh.ru/browse/ADAPT-90
=> ADAPT-90 upgrade scheduler

backend/src/main/java/ru/hh/school/adaptation/services/ScheduledMailService.java
https://jira.hh.ru/browse/ADAPT-93
=> ADAPT-93 spam for chief tasks

frontend/src/components/ListEmployees.js, frontend/src/constants/stepDescription.js
https://jira.hh.ru/browse/ADAPT-65
Поправил сортировку в списке сотрудников
=> ADAPT-65 fix employee list sorting
